Finish adding the update and delete features
acmucsd-projects/team-piplup-wi22 pull request #5
Opened 2022-02-26 04:32 UTC by dowhep

2022-02-26 05:53 UTC, shravanhariharan2 requested changes

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +
Let's use `const` here instead of `let`, since the `Event` and `User` objects do not need to be re-assigned. See this article for info regarding `let` vs. `const` vs. `var`: https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +    const { id, update } = req.params;
Since this function will be performing asynchronous operations (e.g. with `findByIdAndUpdate`), it needs to be marked as `async`.
```suggestion
router.put("/events/:id", async function (req, res) {
  try {
    const { id, update } = req.params;
```

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +    var thisEvent = Event.findByIdAndUpdate(id, update);
Let's avoid the use of `var` since it's a deprecated keyword. We can use `const` instead (since we never need to re-assign this variable).

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +    }
We don't need to use backticks for this string since we aren't using it as a template literal, so let's just use double quotes (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals for details).

Also, 'Event Do Not Exist' -> 'Event does not exist'

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +  }
Let's specify the error that occurred instead of simply returning a string. We can do so by taking in the error in the `catch` block, and returning that error rather than the string 'Server Process Error'. So something like:

```js
} catch (error) {
  res.status(500).json({ error });
}
```

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +  }
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch for syntax reference

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +router.put("/users/:id", function (req, res) {
Let's make this `async` as well

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +    var thisUser = User.findByIdAndUpdate(id, update);
var -> const

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +      return res.status(404).json({ error: `User Do Not Exist`, id });
Same as above, we can remove backticks and rename to 'User does not exist'

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +});
I see that you used similar syntax to what I gave as reference earlier, but we can actually write this route similar to how you wrote the previous routes with `PUT`. Part of writing good quality code is being consistent across functions, so let's aim to follow similar patterns across routes.

Instead of using the `...then()...catch()` syntax, let's use `async/await` like we did above. The code should mostly be the same as above, but with `findByIdAndDelete()` instead of `findByIdAndUpdate()`.

2022-02-26 05:53 UTC, shravanhariharan2 commented on server/routes/users.js
> +});
Same comment as above

2022-02-26 06:14 UTC, dowhep commented
I wonder if I am supposed to resolve reviews (similar to a checklist) or not...

2022-03-01 19:51 UTC, shravanhariharan2 approved these changes
Looks great! Nice work. For review comments, you don't necessarily need to mark each as resolved, whatever helps you keep track of what's already been resolved vs. what needs to be resolved should be good enough.

2022-03-01 19:56 UTC, merged